services:
  - type: web
    name: agent-ia-flutter-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: API_URL
        value: https://ai-agent-uqxt.onrender.com
        # À remplacer par l'URL réelle de votre backend après déploiement
