# Generated by Django 5.0.6 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatistiqueRegionale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Dakar", "Dakar"),
                            ("Thiès", "Thiès"),
                            ("Diourbel", "Diourbel"),
                            ("Fatick", "Fatick"),
                            ("Kaolack", "Kaolack"),
                            ("Kaffrine", "Kaffrine"),
                            ("Kolda", "Kolda"),
                            ("Kédougou", "Kédougou"),
                            ("Louga", "Louga"),
                            ("Matam", "Matam"),
                            ("Saint-Louis", "Saint-Louis"),
                            ("Sédhiou", "Sédhiou"),
                            ("Tambacounda", "Tambacounda"),
                            ("Ziguinchor", "Ziguinchor"),
                        ],
                        help_text="Nom exact de la région (liste blanche des 14 régions du Sénégal).",
                        max_length=40,
                    ),
                ),
                (
                    "annee",
                    models.PositiveSmallIntegerField(
                        help_text="Année de l'observation (2020 à 2024)."
                    ),
                ),
                (
                    "population",
                    models.PositiveBigIntegerField(
                        help_text="Population totale de la région (personnes)."
                    ),
                ),
                (
                    "taux_urbanisation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux d'urbanisation (%).",
                        max_digits=6,
                    ),
                ),
                (
                    "taux_alphabetisation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux d'alphabétisation (%).",
                        max_digits=6,
                    ),
                ),
                (
                    "taux_chomage_pct",
                    models.DecimalField(
                        decimal_places=2, help_text="Taux de chômage (%).", max_digits=6
                    ),
                ),
                (
                    "taux_pauvrete_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux de pauvreté (%).",
                        max_digits=6,
                    ),
                ),
                (
                    "acces_internet_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux d'accès à Internet (%).",
                        max_digits=6,
                    ),
                ),
                (
                    "centres_sante",
                    models.PositiveIntegerField(
                        help_text="Nombre de centres de santé (établissements)."
                    ),
                ),
                (
                    "taux_scolarisation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux de scolarisation (%).",
                        max_digits=6,
                    ),
                ),
                (
                    "production_cerealiere_tonnes",
                    models.PositiveIntegerField(
                        help_text="Production céréalière (tonnes)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique régionale",
                "verbose_name_plural": "Statistiques régionales",
                "ordering": ["region", "annee"],
            },
        ),
        migrations.AddConstraint(
            model_name="statistiqueregionale",
            constraint=models.UniqueConstraint(
                fields=("region", "annee"), name="unique_region_annee"
            ),
        ),
    ]
